### ISSUE TITLE
KMS not responding

### ISSUE THREAD

**Issue by Oratorian** [SystemRage/py-kms#11]
I tried running py-kms with python3 and 2 both give me the same error after the last git pull

`/usr/bin/python /opt/py-kms/py2-kms/server.py -s -v DEBUG
Client sending
===============>                Server received RPC Bind Request !!!
                                Server parsing RPC Bind Request...
                                Server generating RPC Bind Response...
Client receiving
<===============                Server sending RPC Bind Response...
                                RPC Bind acknowledged !!!

Client sending
===============>                Server received RPC Activation Request !!!
                                Server parsing RPC Activation Request...
                                Server processing KMS Activation Request...
----------------------------------------
Exception happened during processing of request from ('95.xx.83.xx', 42209)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/py-kms/py2-kms/server.py", line 158, in handle
    res = str(handler.populate())
  File "/opt/py-kms/py2-kms/rpcBase.py", line 42, in populate
    return self.generateResponse(self.parseRequest())
  File "/opt/py-kms/py2-kms/rpcRequest.py", line 21, in generateResponse
    responseData = kmsBase.generateKmsResponseData(request['pduData'], self.config)
  File "/opt/py-kms/py2-kms/kmsBase.py", line 329, in generateKmsResponseData
    return messagehandler.executeRequestLogic()
  File "/opt/py-kms/py2-kms/kmsRequestV5.py", line 71, in executeRequestLogic
    responseBuffer = self.serverLogic(decrypted['request'])
  File "/opt/py-kms/py2-kms/kmsBase.py", line 177, in serverLogic
    count = int(kmsitem['NCountPolicy'])
ValueError: invalid literal for int() with base 10: ''
----------------------------------------
Client sending
===============>                Server received RPC Bind Request !!!
                                Server parsing RPC Bind Request...
                                Server generating RPC Bind Response...
Client receiving
<===============                Server sending RPC Bind Response...
                                RPC Bind acknowledged !!!

Client sending
===============>                Server received RPC Activation Request !!!
                                Server parsing RPC Activation Request...
                                Server processing KMS Activation Request...
----------------------------------------
Exception happened during processing of request from ('95.xx.83.xx', 59443)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/py-kms/py2-kms/server.py", line 158, in handle
    res = str(handler.populate())
  File "/opt/py-kms/py2-kms/rpcBase.py", line 42, in populate
    return self.generateResponse(self.parseRequest())
  File "/opt/py-kms/py2-kms/rpcRequest.py", line 21, in generateResponse
    responseData = kmsBase.generateKmsResponseData(request['pduData'], self.config)
  File "/opt/py-kms/py2-kms/kmsBase.py", line 329, in generateKmsResponseData
    return messagehandler.executeRequestLogic()
  File "/opt/py-kms/py2-kms/kmsRequestV5.py", line 71, in executeRequestLogic
    responseBuffer = self.serverLogic(decrypted['request'])
  File "/opt/py-kms/py2-kms/kmsBase.py", line 177, in serverLogic
    count = int(kmsitem['NCountPolicy'])
ValueError: invalid literal for int() with base 10: ''
----------------------------------------`

**Comment by Oratorian** [comment]
I tested the KMS server in the folder previous "py-kms_2018_11_15.zip" all KMS Server in there just work fine

**Comment by SystemRage** [comment]
@ricktendo 
do you have enabled your firewall ?

**Comment by ricktendo** [comment]
I just updated to the latest version, activated successfully
