### ISSUE TITLE
systemed keeps crashing

### ISSUE THREAD

**Issue by click23** [SystemRage/py-kms#149]
Hi there ...
I tried to make the py-kms server with systemed on ubuntu and checked everything on the internet and git but, it keeps CRASHING.
1 out of 5 times I checked the service status, it's crashed.

Here is the log on system status.

```
Oct 26 06:35:44 kms systemd[1]: Started py3-kms.
root@kms:/kms# sudo systemctl status py3-kms.service
● py3-kms.service - py3-kms
     Loaded: loaded (/etc/systemd/system/py3-kms.service; static)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-10-26 06:42:22 UTC; 483ms ago
    Process: 3742 ExecStart=/usr/bin/python3 /kms/pykms_Server.py 192.168.131.133 1688 -V DEBUG -F /kms/pykms_logserver.log (code=exited, status=1/FAILURE)
   Main PID: 3742 (code=exited, status=1/FAILURE)
        CPU: 134ms
root@kms:/kms# sudo systemctl status py3-kms.service
● py3-kms.service - py3-kms
     Loaded: loaded (/etc/systemd/system/py3-kms.service; static)
     Active: active (running) since Wed 2022-10-26 06:42:23 UTC; 34ms ago
   Main PID: 3747 (python3)
      Tasks: 1 (limit: 2200)
     Memory: 5.3M
        CPU: 33ms
     CGroup: /system.slice/py3-kms.service
             └─3747 /usr/bin/python3 /kms/pykms_Server.py 192.168.131.133 1688 -V DEBUG -F /kms/pykms_logserver.log

Oct 26 06:42:23 kms systemd[1]: Started py3-kms.
root@kms:/kms# sudo systemctl status py3-kms.service
● py3-kms.service - py3-kms
     Loaded: loaded (/etc/systemd/system/py3-kms.service; static)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-10-26 06:42:23 UTC; 475ms ago
    Process: 3747 ExecStart=/usr/bin/python3 /kms/pykms_Server.py 192.168.131.133 1688 -V DEBUG -F /kms/pykms_logserver.log (code=exited, status=1/FAILURE)
   Main PID: 3747 (code=exited, status=1/FAILURE)
        CPU: 135ms
```
Is it a **BUG** or am I missing something? All permissions are 777 to be sure and everything is been checked 10 times due to the Manual.

**BTW the log file permission is also 777 but it's completely empty.**

**Etrigan also, didn't work ...**

```
Traceback (most recent call last):
  File "/kms/pykms_Server.py", line 27, in <module>
    from Etrigan import Etrigan, Etrigan_parser, Etrigan_check, Etrigan_job
  File "/kms/Etrigan.py", line 12, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by click23** [comment]
BTW the log file permission is also 777 but it's completely empty.

**Comment by click23** [comment]
Etrigan also, didn't work ...

```
Traceback (most recent call last):
  File "/kms/pykms_Server.py", line 27, in <module>
    from Etrigan import Etrigan, Etrigan_parser, Etrigan_check, Etrigan_job
  File "/kms/Etrigan.py", line 12, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by simonmicro** [comment]
See #144 , I think we had fixed that in the fork / you may need an older Python version to still use this repo...
