### ISSUE TITLE
[ Install Script ] Freenas Jail

### ISSUE THREAD

**Issue by Ornias1993** [SystemRage/py-kms#56]
Fpr those interested in a copy paste solution to get py-kms running.
Loosely based on my own personal script (https://github.com/Ornias1993/Freenas-Setup/blob/master/install/kms.sh) 

This script creates a basic (default) jail (named "kms") and installs py-kms as a service on Freenas 11.3U1. 
Logs are stored under /config (easy to put into a seperate external dataset and with room for future config files)

How to?
Create both files in a directory and run ./kms.sh, be happy about it.

#### ./kms.sh
```
echo '{"pkgs":["bash","ca_root_nss","nano","py37-tkinter","py37-pip","py37-sqlite3","git"]}' > /tmp/pkg.json
iocage create -n "kms" -p /tmp/pkg.json -r 11.3-RELEASE dhcp=on" allow_raw_sockets="1" boot="on"
rm /tmp/pkg.json
iocage exec kms mkdir -p /config
iocage exec kms svn checkout https://github.com/SystemRage/py-kms/trunk/py-kms /usr/local/share/py-kms
iocage exec kms "pw user add kms -c kms -u 666 -d /nonexistent -s /usr/bin/nologin"
iocage exec kms chown -R kms:kms /usr/local/share/py-kms /config
iocage exec kms mkdir /usr/local/etc/rc.d
cp ./py_kms /mnt/tank/iocage/jails/kms/root/usr/local/etc/rc.d/py_kms
iocage exec kms chmod u+x /usr/local/etc/rc.d/py_kms
iocage exec kms sysrc "py_kms_enable=YES"
iocage exec kms service py_kms start
```

#### ./py_kms
```
#!/bin/sh

# $FreeBSD$
#
# PROVIDE: py_kms
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# py-kms_enable: Set to YES to enable py-kms
# Default: NO
# py-kms_user: The user account used to run the py-kms daemon.
# This is optional, however do not specifically set this to an
# empty string as this will cause the daemon to run as root.
# Default: media
# py-kms_group: The group account used to run the py-kms daemon.
# This is optional, however do not specifically set this to an
# empty string as this will cause the daemon to run with group wheel.
# Default: media
# py-kms_data_dir: Directory where py-kms configuration
# data is stored.

. /etc/rc.subr
name=py_kms
rcvar=${name}_enable
load_rc_config $name

: ${py_kms_enable:="NO"}
: ${py_kms_user:="kms"}
: ${py_kms_group:="kms"}
: ${py_kms_data_dir:="/config"}

command="/usr/local/bin/python3.7"
command_args="/usr/local/share/py-kms/pykms_Server.py 0.0.0.0 1688 -F ${py_kms_data_dir}/py-kms.log etrigan start --etrigan-pid ${py_kms_data_dir}/etrigan.pid"

run_rc_command "$1"
```

Hereby both files are co-licenced "Unlicence", so Maintainers are free to do with this as they please! :)
I suggest a Wiki article, Freenas plugin creation or including the code.
In any case it has now been documented here for future interested parties!

**Comment by SystemRage** [comment]
Added as documentation.

**Comment by frinus** [comment]
Please change/complete the script [py_kms] to prevent the following error:

`root@kms:/# service py_kms start`
```
Starting py_kms.
Traceback (most recent call last):
  File "/usr/local/share/py-kms/pykms_Server.py", line 640, in <module>
    server_main_terminal()
  File "/usr/local/share/py-kms/pykms_Server.py", line 562, in server_main_terminal
    server_daemon()
  File "/usr/local/share/py-kms/pykms_Server.py", line 392, in server_daemon
    mute = srv_config['etriganmute'], pause_loop = None)
  File "/usr/local/share/py-kms/Etrigan.py", line 120, in __init__
    self.setup_files()
  File "/usr/local/share/py-kms/Etrigan.py", line 146, in setup_files
    filehandler = logging.FileHandler(self.logfile)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/etrigan.log'
/usr/local/etc/rc.d/py_kms: WARNING: failed to start py_kms
```
**./py_kms**

```
-command_args="/usr/local/share/py-kms/pykms_Server.py 0.0.0.0 1688 -F ${py_kms_data_dir}/py-kms.log etrigan start --etrigan-pid ${py_kms_data_dir}/etrigan.pid"
+command_args="/usr/local/share/py-kms/pykms_Server.py 0.0.0.0 1688 -F ${py_kms_data_dir}/py-kms.log etrigan start --etrigan-pid ${py_kms_data_dir}/etrigan.pid --etrigan-log ${py_kms_data_dir}/etrigan.log"
```
Tested under TrueNAS Core 12.0
